{{- if .Values.ingress.enabled }}
{{- $fullName := include "hello-world-go.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-world-go.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: hello-world-go-cors, hello-world-go-claims
    {{- include "hello-world-go.ingress.annotations" . | nindent 4 }}
spec:
  {{- include "hello-world-go.ingress.tls" . | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.hostName }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /hello-world-go
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
