apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-go.fullname" . }}
  labels:
    {{- include "hello-world-go.labels" . | nindent 4 }}
  annotations:
    konghq.com/plugins: hello-world-go-oidc
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port | required "service.port required" }}
  selector:
    {{- include "hello-world-go.selectorLabels" . | nindent 4 }}
